import {HOME_TEAM,AWAY_TEAM} from './inning-teams.js';
// 세 경기, 세 기술. 1은 타이밍(직구·존 안 위주), 2는 조준(낮고 바깥으로 빠지는 변화구), 3은 힘(2사 주자 없음 동점: 홈런 아니면 안타 둘).
export const STAGES=[
 {id:0,skill:'timing',skillLabel:'타이밍',lesson:'직구 위주에 존 안 승부. 초록 구간에서 놓으면 됩니다.',title:'항구의 마지막 공격',situation:'1사 1·2루 · 두 점 차',home:HOME_TEAM,away:AWAY_TEAM,homeScore:0,awayScore:2,outs:1,balls:0,strikes:0,bases:[true,true,false],park:{name:'항구 파크',capacity:18000,weather:'clear'},colors:{home:'#cf7756',away:'#427c83'},pitcher:{name:'강태오',style:'직구파',fast:.70,speedOffset:0,zoneShift:.10,lowBias:.22,edgeX:.30}},
 {id:1,skill:'aim',skillLabel:'조준',lesson:'낮고 바깥으로 빠지는 변화구. 당긴 채 끌어 배트를 공 높이에 맞추세요.',title:'산성의 한 점 승부',outfieldArm:32,situation:'동점 · 1사 3루',home:AWAY_TEAM,away:{name:'숲길 디어스',short:'숲길'},homeScore:2,awayScore:2,outs:1,balls:0,strikes:0,bases:[false,false,true],runnerSpeed:[0,0,7.8],park:{name:'산성 필드',capacity:22000,weather:'evening',fL:103,fC:127,fR:103,fH:3.5},colors:{home:'#427c83',away:'#a58a50'},pitcher:{name:'정하린',style:'변화구파',fast:.30,speedOffset:0,zoneShift:-.12,lowBias:.62,edgeX:.85}},
 {id:2,skill:'power',skillLabel:'힘',lesson:'2사 주자 없음, 동점, 강속구. 홈런이 아니면 안타 둘이 필요합니다. 길게 당겨 장타를 노리세요.',title:'돔의 마지막 타자',situation:'동점 · 2사 주자 없음',home:{name:'도심 스파크',short:'도심'},away:HOME_TEAM,homeScore:4,awayScore:4,outs:2,balls:0,strikes:0,bases:[false,false,false],park:{name:'센트럴 돔',capacity:30000,dome:true,fL:100,fC:123,fR:100,fH:3},colors:{home:'#7561a6',away:'#cf7756'},pitcher:{name:'차민혁',style:'강속구파',fast:.60,speedOffset:5,zoneShift:.06,lowBias:.30,edgeX:.35}},
];
export function getStage(id=0){if(!Number.isInteger(id)||!STAGES[id])throw new Error('Invalid stage');return STAGES[id];}
export function clearedStages(){try{return JSON.parse(localStorage.getItem('dugout.stages.v1')||'[]').filter(id=>Number.isInteger(id)&&STAGES[id]);}catch{return [];}}
export function clearStage(id){getStage(id);try{localStorage.setItem('dugout.stages.v1',JSON.stringify([...new Set([...clearedStages(),id])]));}catch{}if(typeof document!=='undefined')document.dispatchEvent(new Event('dugout-stage-clear'));}
